server:
  port: 8080
  address: 0.0.0.0

jwt:
  secret: "muCWlNPM9ze589S2yDzhxIgHRzwSkbBb/PuTiMtmEKvhzeCHcS/nMaWrfKbvAdmw/nLwX6Pa5XrPOpCKXPdujw=="
  expiration: 86400000


spring:
    application:
        name: masServer
    datasource:
        url: jdbc:postgresql://localhost:5432/mas_db
        username: biomas_user
        password: securepassword
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    security:
        DEBUG: true

    mail:
        host: smtp.zoho.in
        port: 587
        username: kalashkumar@zohomail.in
        password: irsYGj77e9Jq
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
      

minio:
    url: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: mas-files


logging:
  level:
    org:
      springframework:
        web:
          socket: TRACE            # trace low-level WebSocket handshake activity
          socket.sockjs: TRACE      # trace SockJS fallback transport behavior
          socket.handler: TRACE     # trace SockJS frame handler details
        messaging:
          simp: DEBUG               # log STOMP messages routing & broker events
          support: DEBUG            # internal message support components
    com:
      mas:
        masServer:
          config:
            JwtChannelInterceptor: DEBUG
            WebSocketConfig: DEBUG
            JwtHandShakeInterceptor: DEBUG
            JwtUtil: DEBUG
            WebSocketSecurityConfig: DEBUG
          service:
            HeartbeatService: DEBUG
            WebSocketEventListener: DEBUG
            HeartbeatScheduler: DEBUG

          controller:
            HeartbeatController: DEBUG
          security:
            JwtAuthenticationFilter: DEBUG
          masServer: INFO

  file:
    name: logs/websocket.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
      total-size-cap: 50MB
      clean-history-on-start: true

BIOMETRIC_AES_KEY: "4uZ+Rz6pZ9oX6qZf5cE+ZbP6ZV4w7Gx+0Xxqg7kC0rU="


security:
  biometric:
    aes:
      key: ${BIOMETRIC_AES_KEY}  # Base64 encoded 32-byte key

external:
  fingerprint:
    base-url: http://10.14.75.89:5188/api/fingerprint



